# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            DVAPX
tagline:          Data, Visualization, ...
url:              http://gaursrbh.github.io
paginate:         1
baseurl:          /
author:
  name:           Saurabh Gaur
  url:            https://twitter.com/srbhgaur
  email:          srbhgaur@gmail.com
